vich_uploader:
    db_driver: orm

    mappings:
        pastes:
            uri_prefix: /images/pastes
            upload_destination: '%kernel.project_dir%/public/images/pastes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        caps:
            uri_prefix: /images/caps
            upload_destination: '%kernel.project_dir%/public/images/caps'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer    